//! Integration test: verify that the Rust witness solver produces byte-exact
//! output matching the nargo reference witness.
//!
//! Fixtures (generated by `scripts/generate_reference_fixture.py`):
//!   tests/fixtures/reference_circuit.json   — compiled Noir circuit artifact
//!   tests/fixtures/reference_inputs.json    — JSON inputs (same as stdin)
//!   tests/fixtures/reference_witness.msgpack — nargo's raw msgpack output
//!
//! This test does NOT require nargo, bb, or any external tool at test time.
//! It exercises the full Rust pipeline: JSON parsing → ACVM solve →
//! msgpack serialization, then asserts byte-for-byte parity with nargo.

use obscura_prover::{serialize_witness_stack_msgpack, solve_witness};
use std::fs;
use std::path::PathBuf;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

/// Returns true if all three fixture files exist. If any are missing,
/// the test is skipped with a message (not a failure) so CI doesn't
/// break before fixtures are generated.
fn fixtures_present() -> bool {
    let dir = fixtures_dir();
    let needed = [
        "reference_circuit.json",
        "reference_inputs.json",
        "reference_witness.msgpack",
    ];
    for name in &needed {
        if !dir.join(name).is_file() {
            eprintln!(
                "[skip] fixture missing: tests/fixtures/{name}\n\
                 Run: python3 scripts/generate_reference_fixture.py"
            );
            return false;
        }
    }
    true
}

#[test]
fn rust_witness_matches_nargo_reference() {
    if !fixtures_present() {
        eprintln!("[witness_compatibility] Skipping — fixtures not generated yet.");
        return;
    }

    let dir = fixtures_dir();

    // ── Load fixtures ───────────────────────────────────────────────────
    let circuit_json =
        fs::read_to_string(dir.join("reference_circuit.json")).expect("read circuit");
    let inputs_json =
        fs::read_to_string(dir.join("reference_inputs.json")).expect("read inputs");
    let expected_msgpack =
        fs::read(dir.join("reference_witness.msgpack")).expect("read witness");

    // ── Solve via Rust library ──────────────────────────────────────────
    let solved = solve_witness(&circuit_json, &inputs_json)
        .expect("solve_witness should succeed on reference inputs");

    let actual_msgpack = serialize_witness_stack_msgpack(&solved.entries);

    // ── Compare ─────────────────────────────────────────────────────────
    assert_eq!(
        actual_msgpack.len(),
        expected_msgpack.len(),
        "msgpack length mismatch: Rust produced {} bytes, nargo reference is {} bytes",
        actual_msgpack.len(),
        expected_msgpack.len(),
    );

    // Find first divergent byte for a useful error message.
    let first_diff = actual_msgpack
        .iter()
        .zip(expected_msgpack.iter())
        .position(|(a, b)| a != b);

    if let Some(offset) = first_diff {
        // Build hex context window around the mismatch.
        let lo = offset.saturating_sub(8);
        let hi = (offset + 9).min(actual_msgpack.len());

        let rust_hex: String = actual_msgpack[lo..hi]
            .iter()
            .enumerate()
            .map(|(i, b)| {
                if lo + i == offset {
                    format!("[{b:02x}]")
                } else {
                    format!(" {b:02x} ")
                }
            })
            .collect();

        let nargo_hex: String = expected_msgpack[lo..hi]
            .iter()
            .enumerate()
            .map(|(i, b)| {
                if lo + i == offset {
                    format!("[{b:02x}]")
                } else {
                    format!(" {b:02x} ")
                }
            })
            .collect();

        panic!(
            "Byte mismatch at offset {offset}:\n\
             Rust  (offsets {lo}..{hi}): {rust_hex}\n\
             Nargo (offsets {lo}..{hi}): {nargo_hex}\n\
             \n\
             This means the Rust msgpack serializer diverges from nargo.\n\
             Check serialize_witness_stack_msgpack() in src/lib.rs."
        );
    }

    // Lengths match and no byte differs — bit-identical.
    eprintln!(
        "[witness_compatibility] PASS — {} bytes, bit-identical to nargo reference.",
        actual_msgpack.len()
    );
}

#[test]
fn solve_witness_rejects_bad_version() {
    if !fixtures_present() {
        return;
    }

    let dir = fixtures_dir();
    let mut circuit_json: serde_json::Value =
        serde_json::from_str(
            &fs::read_to_string(dir.join("reference_circuit.json")).unwrap(),
        )
        .unwrap();

    // Tamper the noir_version to something unsupported.
    circuit_json["noir_version"] = serde_json::json!("99.99.99");

    let inputs_json =
        fs::read_to_string(dir.join("reference_inputs.json")).unwrap();

    let result = solve_witness(&circuit_json.to_string(), &inputs_json);
    assert!(result.is_err(), "should reject unsupported noir version");
    assert!(
        result.unwrap_err().contains("Unsupported noir version"),
        "error should mention version mismatch"
    );
}
