#!/usr/bin/env python3
"""
Generate HD key derivation test vectors for cross-language parity testing.

Computes derive_note_sk for known seeds and indices using the same
PBKDF2-HMAC-SHA512 formula as tonkl_wallet.py, then prints the results as Rust
test constants. Run this once, paste the output into lib.rs tests.

Usage:
    python3 scripts/generate_hd_test_vectors.py
"""

import hashlib

BN254_P = 21888242871839275222246405745257275088548364400416034343698204186575808495617
DERIVATION_DOMAIN = b"Tonkl::note_sk_v1"


def derive_note_sk(seed: bytes, index: int) -> bytes:
    assert len(seed) == 64, f"seed must be 64 bytes, got {len(seed)}"
    derive_input = DERIVATION_DOMAIN + seed + index.to_bytes(8, "big")
    raw = hashlib.pbkdf2_hmac("sha512", derive_input, DERIVATION_DOMAIN, 1)[:32]
    sk_int = int.from_bytes(raw, "big") % BN254_P
    return sk_int.to_bytes(32, "big")


# Test vectors with known seeds
vectors = [
    # (seed_hex, index, description)
    ("ab" * 64, 0, "all-0xAB seed, index 0"),
    ("ab" * 64, 1, "all-0xAB seed, index 1"),
    ("42" * 64, 0, "all-0x42 seed, index 0"),
    ("42" * 64, 99, "all-0x42 seed, index 99"),
    ("00" * 64, 0, "all-zero seed, index 0"),
]

print("// HD key derivation test vectors (generated by scripts/generate_hd_test_vectors.py)")
print("// KDF: PBKDF2-HMAC-SHA512, iterations=1, salt=Tonkl::note_sk_v1")
print()

for seed_hex, index, desc in vectors:
    seed = bytes.fromhex(seed_hex)
    sk = derive_note_sk(seed, index)
    sk_hex = sk.hex()
    print(f"// {desc}")
    print(f"// seed: {seed_hex[:16]}...  index: {index}")
    print(f"// sk  : {sk_hex}")

    # Print as Rust byte array for pasting into tests
    byte_strs = [f"0x{sk_hex[i:i+2]}" for i in range(0, 64, 2)]
    print(f"// Rust: [{', '.join(byte_strs)}]")
    print()

# Also print as a compact Rust test
print("// Copy-paste into lib.rs tests for cross-language parity:")
print("#[test]")
print("fn derive_note_sk_cross_language_parity() {")
for seed_hex, index, desc in vectors:
    seed = bytes.fromhex(seed_hex)
    sk = derive_note_sk(seed, index)
    sk_hex = sk.hex()
    seed_pat = f"0x{seed_hex[:2].upper()}"
    print(f'    // {desc}')
    print(f'    assert_eq!(')
    print(f'        derive_note_sk(&[{seed_pat}u8; 64], {index}),')
    byte_strs = [f"0x{sk_hex[i:i+2]}" for i in range(0, 64, 2)]
    # Split into 8-byte chunks for readability
    chunks = [byte_strs[i:i+8] for i in range(0, 32, 8)]
    print(f'        [')
    for chunk in chunks:
        print(f'            {", ".join(chunk)},')
    print(f'        ]')
    print(f'    );')
print("}")
