#!/usr/bin/env python3
"""
Generate HD key derivation test vectors for cross-language parity testing.

Computes derive_note_sk for known seeds and indices using the same BLAKE3
formula as secure_key_manager.py, then prints the results as Rust test
constants. Run this once, paste the output into lib.rs tests.

Usage:
    python3 scripts/generate_hd_test_vectors.py
"""

import hashlib
import hmac

BN254_P = 21888242871839275222246405745257275088548364400416034343698204186575808495617
DERIVATION_DOMAIN = b"Tonkl::note_sk_v1"

try:
    import blake3 as _blake3
    HAS_BLAKE3 = True
except ImportError:
    HAS_BLAKE3 = False

def derive_hash(data: bytes) -> bytes:
    if HAS_BLAKE3:
        return _blake3.blake3(data).digest()
    else:
        return hmac.new(DERIVATION_DOMAIN, data, hashlib.sha512).digest()[:32]

def derive_note_sk(seed: bytes, index: int) -> bytes:
    assert len(seed) == 64, f"seed must be 64 bytes, got {len(seed)}"
    raw = derive_hash(DERIVATION_DOMAIN + seed + index.to_bytes(8, "big"))
    sk_int = int.from_bytes(raw, "big") % BN254_P
    return sk_int.to_bytes(32, "big")


# Test vectors with known seeds
vectors = [
    # (seed_hex, index, description)
    ("ab" * 64, 0, "all-0xAB seed, index 0"),
    ("ab" * 64, 1, "all-0xAB seed, index 1"),
    ("42" * 64, 0, "all-0x42 seed, index 0"),
    ("42" * 64, 99, "all-0x42 seed, index 99"),
    ("00" * 64, 0, "all-zero seed, index 0"),
]

if not HAS_BLAKE3:
    print("WARNING: blake3 not installed, using HMAC-SHA512 fallback.")
    print("         Install blake3: pip install blake3")
    print("         Results will NOT match the Rust implementation!")
    print()

print("// HD key derivation test vectors (generated by scripts/generate_hd_test_vectors.py)")
print("// Hash function: BLAKE3" if HAS_BLAKE3 else "// Hash function: HMAC-SHA512 (FALLBACK)")
print()

for seed_hex, index, desc in vectors:
    seed = bytes.fromhex(seed_hex)
    sk = derive_note_sk(seed, index)
    sk_hex = sk.hex()
    print(f"// {desc}")
    print(f"// seed: {seed_hex[:16]}...  index: {index}")
    print(f"// sk  : {sk_hex}")

    # Print as Rust byte array for pasting into tests
    byte_strs = [f"0x{sk_hex[i:i+2]}" for i in range(0, 64, 2)]
    print(f"// Rust: [{', '.join(byte_strs)}]")
    print()

# Also print as a compact Rust test
print("// Copy-paste into lib.rs tests for cross-language parity:")
print("#[test]")
print("fn derive_note_sk_cross_language_parity() {")
for seed_hex, index, desc in vectors:
    seed = bytes.fromhex(seed_hex)
    sk = derive_note_sk(seed, index)
    sk_hex = sk.hex()
    seed_pat = f"0x{seed_hex[:2].upper()}"
    print(f'    // {desc}')
    print(f'    assert_eq!(')
    print(f'        derive_note_sk(&[{seed_pat}u8; 64], {index}),')
    byte_strs = [f"0x{sk_hex[i:i+2]}" for i in range(0, 64, 2)]
    # Split into 8-byte chunks for readability
    chunks = [byte_strs[i:i+8] for i in range(0, 32, 8)]
    print(f'        [')
    for chunk in chunks:
        print(f'            {", ".join(chunk)},')
    print(f'        ]')
    print(f'    );')
print("}")
